-- 이력서 테이블 생성
CREATE TABLE "RESUME" 
   (	"ID" NUMBER(20,0), 
	"USER_ID" VARCHAR2(100), 
	"CAREER" VARCHAR2(100), 
	"SCHOOL" VARCHAR2(100), 
	"PORTFOLIO" VARCHAR2(100), 
	"REG_DATE" VARCHAR2(100), 
	"LICENCE" VARCHAR2(100)
   );
   
-- 시퀀스 생성
CREATE SEQUENCE resume_seq
	START WITH 1 INCREMENT BY 1;